FROM node:20-bullseye

WORKDIR /app/web

RUN apt-get update && apt-get install -y curl bash git \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:/pnpm/bin:$PATH

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "dev"]