version: "3.9"

services:
  frontend:
    build:
      context: ./apps/web
    container_name: claudable_frontend
    ports:
      - "5090:3000" # 前端改 5090
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4090
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/api
    container_name: claudable_backend
    ports:
      - "4090:8080" # 後端改 4090
    volumes:
      - ./apps/api:/app/api
      - ./data:/app/api/data
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PORT=8080
      - HOME=/root
      - CLAUDE_HOME=/root/.claude
      - CURSOR_HOME=/root/.local/share/cursor-agent

volumes:
  claude_data:
  codex_data:
  qwen_data:
  gemini_data:
  cursor_data:
  openai_data:
