services:
  # 互動登入：只在 --profile auth 時才會啟動
  login:
    container_name: claudable_login
    profiles: ["auth"]
    build:
      context: ./apps/api
      dockerfile: dockerfile
    environment:
      HOME: /root
      XDG_CONFIG_HOME: /root/.config
      PATH: "/opt/venv/bin:/usr/local/bin:/usr/bin:/bin:/root/.local/bin"
    stdin_open: true
    tty: true
    volumes:
      - ./apps/api:/srv/api

      # Claude 狀態（皆為可寫 named volumes）
      - claude_plugins:/root/.claude/plugins
      - claude_projects:/root/.claude/projects
      - claude_sessions:/root/.claude/sessions

      # Gemini / Qwen / Cursor / Codex（OpenAI）狀態（可寫）
      - gemini_home:/root/.gemini
      - gemini_state:/root/.config/gemini
      - qwen_state:/root/.qwen
      - cursor_data:/root/.local/share/cursor-agent
      - cursor_config:/root/.config/cursor-agent
      - openai_state:/root/.config/openai

    working_dir: /srv/api
    # 這個腳本只做「檢查＋必要時啟動互動登入」，若都已就緒會直接退出 0
    command: ["/bin/bash","-lc","/usr/local/bin/ai-login-check.sh"]

  backend:
    container_name: claudable_backend
    build:
      context: ./apps/api
      dockerfile: dockerfile
    ports:
      - "4090:8080"
    env_file:
      - .env
    environment:
      HOME: /root
      XDG_CONFIG_HOME: /root/.config
      PORT: 8080
      PROJECTS_ROOT: /srv/data/projects
      PROJECTS_ROOT_HOST: /srv/data/projects
      PATH: "/opt/venv/bin:/usr/local/bin:/usr/bin:/bin:/root/.local/bin"

    # 注意：不再依賴 login（因為 login 只在 profile: auth 時會被啟動）
    volumes:
      - ./apps/api:/srv/api
      - ./data:/srv/data

      # Claude（全部用 named volumes，避免 EROFS）
      - claude_plugins:/root/.claude/plugins
      - claude_projects:/root/.claude/projects
      - claude_sessions:/root/.claude/sessions

      # Gemini / Qwen / Cursor / Codex（OpenAI）狀態
      - gemini_home:/root/.gemini
      - gemini_state:/root/.config/gemini
      - qwen_state:/root/.qwen
      - cursor_data:/root/.local/share/cursor-agent
      - cursor_config:/root/.config/cursor-agent
      - openai_state:/root/.config/openai

      # 啟動輔助腳本（若已 COPY 進 image 可改為不掛載）
      - ./apps/api/bootstrap-cursor.sh:/usr/local/bin/bootstrap-cursor.sh:ro

    working_dir: /srv/api
    command: ["/bin/bash","-lc","/usr/local/bin/bootstrap-cursor.sh uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"]

  frontend:
    container_name: claudable_frontend
    build:
      context: ./apps/web
      dockerfile: dockerfile
    ports:
      - "5090:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4090
      NEXT_PUBLIC_API_BASE: http://localhost:4090
      NEXT_PUBLIC_WS_BASE: ws://localhost:4090
      INTERNAL_API_URL: http://backend:8080
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
      - pnpm_store:/pnpm-store
      - pnpm_state:/pnpm-state
    working_dir: /app
    command: >
      bash -lc "
        corepack enable &&
        pnpm config set store-dir /pnpm-store &&
        pnpm config set state-dir /pnpm-state &&
        pnpm install &&
        pnpm dev -p 3000
      "

volumes:
  web_node_modules: {}
  pnpm_store: {}
  pnpm_state: {}

  # 狀態持久化
  cursor_data: {}
  cursor_config: {}
  claude_plugins: {}
  claude_projects: {}
  claude_sessions: {}
  gemini_home: {}
  gemini_state: {}
  qwen_state: {}
  openai_state: {}