version: "3.9"

services:
  frontend:
    build:
      context: ./apps/web
      dockerfile: dockerfile
    container_name: claudable_frontend
    ports:
      - "5090:3000"      # 前端 -> 5090
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4090
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/api
      dockerfile: dockerfile
    container_name: claudable_backend
    ports:
      - "4090:8080"      # 後端 -> 4090
    # ★★ 掛載「本機憑證資料夾」（只讀）→ 容器內不用再登入
    volumes:
      - ~/.claude:/root/.claude:ro
      - ~/.config/openai:/root/.config/openai:ro
      - ~/.qwen:/root/.qwen:ro
      - ~/.config/gemini:/root/.config/gemini:ro
      - cursor_data:/root/.local/share/cursor-agent
    environment:
      - HOME=/root
      - XDG_CONFIG_HOME=/root/.config
      - PATH=/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin