services:
  frontend:
    container_name: claudable_frontend
    build:
      context: ./apps/web
      dockerfile: dockerfile           # 若你的檔名是 Dockerfile 改成 Dockerfile
    ports:
      - "5090:3000"
    # 前端不要讀 .env（避免把金鑰注入容器）
    environment:
      NODE_ENV: development
      # 給瀏覽器用的公開變數
      NEXT_PUBLIC_API_URL: http://localhost:4090
      NEXT_PUBLIC_API_BASE: http://localhost:4090
      NEXT_PUBLIC_WS_BASE: ws://localhost:4090
      # 伺服器端/SSR 用內部位址，避免 localhost 陷阱
      INTERNAL_API_URL: http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    working_dir: /app
    command: >
      bash -lc "corepack enable &&
                pnpm install &&
                pnpm dev -p 3000"

  backend:
    container_name: claudable_backend
    build:
      context: ./apps/api
      dockerfile: dockerfile           # 若你的檔名是 Dockerfile 改成 Dockerfile
    ports:
      - "4090:8080"
    # 只給 backend 注入祕密
    env_file:
      - .env.backend
    environment:
      HOME: /root
      XDG_CONFIG_HOME: /root/.config
      PORT: 8080
      # 路徑用容器內掛載位置
      PROJECTS_ROOT: /srv/data/projects
      PROJECTS_ROOT_HOST: /srv/data/projects
      # 如果你沒用 Postgres，這些就不要放，避免程式誤判：
      # POSTGRES_HOST: localhost
      # POSTGRES_PORT: "5432"
      # POSTGRES_DB: cc
      # POSTGRES_USER: cc
      # POSTGRES_PASSWORD: cc
    volumes:
      - ./apps/api:/srv/api
      - ./data:/srv/data
      # 可選：沿用本機登入檔（若容器需要自動更新 token，拿掉 :ro）
      - ${HOME}/.claude:/root/.claude:ro
      - ${HOME}/.config/openai:/root/.config/openai:ro
      - ${HOME}/.qwen:/root/.qwen:ro
      - ${HOME}/.config/gemini:/root/.config/gemini:ro
      # cursor-agent 資料卷
      - cursor_data:/root/.local/share/cursor-agent
      # 啟動前置腳本（你已放在 apps/api 了）
      - ./apps/api/bootstrap-cursor.sh:/usr/local/bin/bootstrap-cursor.sh:ro
    working_dir: /srv/api
    command: ["/bin/bash","-lc","/usr/local/bin/bootstrap-cursor.sh uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"]

volumes:
  web_node_modules: {}
  cursor_data: {}
