# docker-compose.yaml
# 說明：
# - login：互動登入前置檢查（Claude→Gemini→Qwen→Codex→Cursor）。全部就緒才放行 backend/frontend。
# - backend：後端 API（在容器內用 bootstrap-cursor.sh 啟動 uvicorn）。
# - frontend：Next.js 開發伺服器，將 pnpm 的 store/state 放在命名卷，避免把 .pnpm-store 推進 Git。
# - 不要加 `version:` 欄位（Compose v2 已不需，避免警告）。

services:
  login:
    container_name: claudable_login
    build:
      context: ./apps/api
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    environment:
      HOME: /root
      XDG_CONFIG_HOME: /root/.config
      PATH: "/opt/venv/bin:/usr/local/bin:/usr/bin:/bin:/root/.local/bin"
      # 可調整的檢查嚴格度／重試次數（必要時在執行時覆寫）
      STRICT_CLAUDE: "0"    # 1=Claude 未檢出登入則阻擋；0=只警示
      STRICT_CODEX: "0"     # 1=Codex 未登入阻擋；0=只警示
      GEMINI_MAX_RUNS: "2"  # Gemini 自動重啟次數（處理首次提示 "Please restart"）
    volumes:
      # 專案程式
      - ./apps/api:/srv/api

      # 登入檢查腳本（login 容器內執行）
      - ./apps/api/scripts/ai-login-check.sh:/usr/local/bin/ai-login-check.sh:ro

      # Claude 狀態（全部用命名卷，確保可寫，避免 EROFS）
      - claude_plugins:/root/.claude/plugins
      - claude_projects:/root/.claude/projects
      - claude_sessions:/root/.claude/sessions

      # Gemini 狀態（新版使用 ~/.gemini；亦保留 ~/.config/gemini）
      - gemini_state:/root/.config/gemini
      - gemini_home:/root/.gemini

      # Qwen / Cursor / Codex（OpenAI）狀態
      - qwen_state:/root/.qwen
      - cursor_data:/root/.local/share/cursor-agent
      - cursor_config:/root/.config/cursor-agent
      - openai_state:/root/.config/openai
    working_dir: /srv/api
    command: ["/bin/bash","-lc","/usr/local/bin/ai-login-check.sh"]

  backend:
    container_name: claudable_backend
    build:
      context: ./apps/api
      dockerfile: dockerfile
    # 非 AI 機密建議放 .env（例如 ENCRYPTION_KEY、DB 等）
    env_file:
      - .env
    environment:
      HOME: /root
      XDG_CONFIG_HOME: /root/.config
      PORT: 8080
      PROJECTS_ROOT: /srv/data/projects
      PROJECTS_ROOT_HOST: /srv/data/projects
      PATH: "/opt/venv/bin:/usr/local/bin:/usr/bin:/bin:/root/.local/bin"
    depends_on:
      login:
        condition: service_completed_successfully
    volumes:
      # 程式與資料
      - ./apps/api:/srv/api
      - ./data:/srv/data

      # Claude 狀態（與 login 共用命名卷）
      - claude_plugins:/root/.claude/plugins
      - claude_projects:/root/.claude/projects
      - claude_sessions:/root/.claude/sessions

      # Gemini / Qwen / Cursor / Codex（OpenAI）狀態
      - gemini_state:/root/.config/gemini
      - gemini_home:/root/.gemini
      - qwen_state:/root/.qwen
      - cursor_data:/root/.local/share/cursor-agent
      - cursor_config:/root/.config/cursor-agent
      - openai_state:/root/.config/openai

      # 啟動腳本（容器內執行）
      - ./apps/api/bootstrap-cursor.sh:/usr/local/bin/bootstrap-cursor.sh:ro
    working_dir: /srv/api
    ports:
      - "4090:8080"
    command: ["/bin/bash","-lc","/usr/local/bin/bootstrap-cursor.sh uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"]

  frontend:
    container_name: claudable_frontend
    build:
      context: ./apps/web
      dockerfile: dockerfile
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4090
      NEXT_PUBLIC_API_BASE: http://localhost:4090
      NEXT_PUBLIC_WS_BASE: ws://localhost:4090
      INTERNAL_API_URL: http://backend:8080
    depends_on:
      backend:
        condition: service_started
    working_dir: /app
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
      - pnpm_store:/pnpm-store
      - pnpm_state:/pnpm-state
    ports:
      - "5090:3000"
    command: >
      bash -lc "
        corepack enable &&
        pnpm config set store-dir /pnpm-store &&
        pnpm config set state-dir /pnpm-state &&
        pnpm install &&
        pnpm dev -p 3000
      "

volumes:
  # 前端依賴快取
  web_node_modules: {}
  pnpm_store: {}
  pnpm_state: {}

  # AI 狀態卷（可寫，避免 EROFS 與 host 權限差異）
  claude_plugins: {}
  claude_projects: {}
  claude_sessions: {}
  gemini_state: {}
  gemini_home: {}
  qwen_state: {}
  cursor_data: {}
  cursor_config: {}
  openai_state: {}
